version: '2'
services:
  web:
    build:
      context: './src/'
      dockerfile: 'not-so-dockerfile.Dockerfile'
    command: "node index.js"
    expose:
      - "5000"
      - "6000"
    ports:
      - "1000"
      - "2000"
      - "3000"
      - "4000"
