version: '2'
services:
  web:
    build:
      context: './src/'
      dockerfile: 'not-so-dockerfile.Dockerfile'
    command: "node index.js"
    expose:
      - "5000"
    ports:
      - "6000:5000"
